Repository openstax/webview, pull requests merged in 2018-10, with the labels that each got.

#1946 issue 1944 add more accessibility to toc
  src/locale/en-US/dictionary.ftl
  src/locale/pl/dictionary.ftl
  src/scripts/modules/media/nav/nav-template.html
  src/scripts/modules/media/tabs/contents/contents-template.html
  src/scripts/modules/media/tabs/contents/toc/section-template.html
  src/scripts/modules/media/tabs/contents/toc/section.less
Labels: review: Phil

#1972 issues 1970 and 1971 - add ellipsis and remove .more button when desc is short enough
  src/scripts/modules/featured-books/featured-books-partial.html
  src/scripts/modules/featured-books/featured-books.coffee
  src/scripts/modules/featured-books/featured-books.less
Labels: review: Adrian

#1985 issue 1626 resize toc to be full width below 640px resolution
  src/scripts/modules/window-with-sidebar/window-with-sidebar.less
Labels: review: Patryk

#1982 issue 1896 disable overflow-anchor (Google Chrome anchor scrolling)
  src/scripts/pages/app/app.less
Labels: review: TomWoodward

#1975 Issue 1944v2
  .jenkins/deploy
  .jenkins/gen_env_list.py
  src/scripts/modules/featured-books/featured-books.less
  src/scripts/modules/media/nav/nav.coffee
  src/scripts/modules/media/tabs/contents/toc/section.coffee
Labels: review: Phil

#1984 issue 1794 encodeURIComponent for exercises tags
  src/scripts/configs/embeddables.coffee
  test/scripts/modules/media/body/body.js
Labels: review: Dantemss

#2009 Issue 2000v2
  src/scripts/modules/media/footer/metadata/metadata.less
Labels: review:Helene

#2016 Deletes default markers in circled class lists
  src/scripts/modules/media/body/content-baked.less
Labels: review:Helene
