Repository openstax/webview, pull requests merged in 2018-08, with the labels that each got.

#1786 move css to content-baked
  src/scripts/modules/media/body/content-baked.less
  src/scripts/modules/media/body/content-common.less
Labels: review:Helene

#1815 Style end notes
  src/scripts/modules/media/body/content-baked.less
Labels: review:BrittanyJ

#1631 Do not strip non-ascii chars from url
  src/scripts/helpers/handlebars/trim.coffee
  test/scripts/helpers/handlebars/trim.js
Labels: rc:demo

#1805 issue 1703 add aria-busy attribute to search view and modify design when searching
  src/scripts/modules/search/search.coffee
  src/scripts/modules/search/search.less
Labels: review: Phil

#1845 issue 1831 / 1840 / 1843 - no padding left for lists inside tables
  src/scripts/modules/media/body/content-baked.less
  src/scripts/modules/media/body/content-common.less
Labels: review:Helene

#1877 Fixed inconsistent displaying of headers of formulas
  src/scripts/modules/media/body/content-baked.less
Labels: review: Adrian, review: Piotr, review:Helene

#1880 Small display change exercises properly
  src/scripts/modules/media/body/content-baked.less
Labels: review: Piotr, review:Helene
