Repository openstax/webview, pull requests merged in 2018-09, with the labels that each got.

#1894 fix image height in about this book section
  src/scripts/modules/media/body/body.less
Labels: bug, prio:high

#1898 Fixed display style of figures in exercises
  src/scripts/modules/media/body/content-baked.less
Labels: review: Adrian

#1893 issue 1883 stay at current scroll position after opening history tab
  src/scripts/modules/media/footer/footer.coffee
Labels: review: Phil

#1932 issue 1829 - disable license view
  src/scripts/modules/media/footer/footer.coffee
Labels: review:Helene

#1929 1902 margin in tables with bullet lists
  src/scripts/modules/media/body/content-baked.less
Labels: review:Helene

#1928 Issue-1911
  src/scripts/modules/media/body/content-common.less
Labels: review:Helene

#1949 issue 1905 show links in book descriptions
  src/scripts/models/featured-openstax-book.coffee
  src/scripts/modules/featured-books/featured-books-partial.html
  src/scripts/modules/featured-books/featured-books.coffee
  src/scripts/modules/featured-books/featured-books.less
Labels: review: Phil

#1961 issue 1757 read solution after open
  src/scripts/modules/media/body/body.coffee
  src/scripts/modules/media/body/content-common.less
Labels: review: Phil
