Repository openstax/webview, pull requests merged in 2019-01, with the labels that each got.

#2156 Bold reference number
  src/scripts/modules/media/body/content-baked.less
Labels: review: Piotr, review:Helene

#2146 added display block to img in end of section problems and solutions
  src/scripts/modules/media/body/content-baked.less
Labels: book:elementary.algebra, book:intermediate.algebra, book:prealgebra

#2145 added margin-top to os-solution-container paragraphs in examples
  src/scripts/modules/media/body/content-baked.less
Labels: book:intermediate.algebra

#2166 changed list style type in review questions to upper alpha
  src/scripts/modules/media/body/content-baked.less
Labels: book:american.government
