Repository openstax/webview, pull requests merged in 2019-04, with the labels that each got.

#2235 fixed answer key display
  src/scripts/modules/media/body/content-baked.less
Labels: book:algebra.and.trigonometry, book:college.algebra, book:precalculus

#2233 set span images display to block
  src/scripts/modules/media/body/content-baked.less
Labels: book:college.algebra, book:precalculus

#2238 changed figcaption display to block so unnumbered captions display correct
  src/scripts/modules/media/body/content-baked.less
Labels: book:algebra.and.trigonometry, book:college.algebra, book:precalculus, review:BrittanyJ, review:Helene

#2246 Remove bullet list from abstract
  src/scripts/modules/media/body/content-baked.less
Labels: review:BrittanyJ
